// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_animal.cpp"
#include "EWIEGA46WW/moc_canino.cpp"
#include "EWIEGA46WW/moc_laptop.cpp"
#include "EWIEGA46WW/moc_mamiferos.cpp"
